-- Session IDs are generated by the session module and may include stable
-- prefixes. Keep language configuration aligned with voice_sessions.id.

ALTER TABLE voice_session_language_configs
    ALTER COLUMN session_id TYPE TEXT;
