"use client";

import { Children, cloneElement, createContext, isValidElement, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";

export type Locale = "zh" | "en";

const translations: Record<string, string> = {
  "让翻译": "Keep interpreting", "不打断对话。": "from interrupting conversation.",
  "面对面同传，": "Face-to-face interpreting,", "临时双语会话与双向听译": "Temporary bilingual sessions and bidirectional interpreting", "Web 主要体验入口": "Primary Web experience", "实时语音、翻译与句末播报": "Real-time speech, translation, and end-of-turn playback", "可扩展的协议与设备控制核心": "Extensible protocols and device control core", "或": "or",
  "Mobile 当前提供可编译、可测试的控制面核心，不包含 UI、PeerConnection 或原生 KWS。": "Mobile currently provides a compilable, testable control core without UI, PeerConnection, or native KWS.", "Device SDK 提供鉴权、会话、模式、唤醒事件和重连边界，具体音频 HAL、WebRTC 与 KWS 模型由平台适配。": "Device SDK defines authentication, sessions, modes, wake events, and reconnect boundaries; the platform adapts the audio HAL, WebRTC, and KWS models.", "Node.js 22 LTS、npm 与 Go 1.26.7。": "Node.js 22 LTS, npm, and Go 1.26.7.", "PostgreSQL 16、Redis/Valkey 7；也可以使用 Docker Desktop 启动它们。": "PostgreSQL 16 and Redis/Valkey 7; Docker Desktop can start them as well.", "不使用 Docker 时，脚本会优先连接 `.env` 中的本地 PostgreSQL 和 Redis；也可以通过": "Without Docker, the script first connects to local PostgreSQL and Redis from `.env`; you can also use", "只启动一个后端服务。": "to start only one backend service.", "Web 默认以 AI 助手模式创建会话；可通过": "Web creates sessions in assistant mode by default; use", "选择同传入口。": "to choose the interpreting entry.", "同时维护 OpenAPI、实时事件、WebRTC 信令边界、错误码、会话状态机以及 Go/TypeScript 绑定。跨端字段先改契约，再改 API、Realtime Audio、Web 或 Device SDK。": "maintains OpenAPI, live events, WebRTC signaling boundaries, error codes, the session state machine, and Go/TypeScript bindings. Change the contract first, then API, Realtime Audio, Web, or Device SDK.", "核心事件包括": "Core events include", "和": "and", "通过": "via", "读取和切换模式，并携带 runtime 与 generation 进行冲突保护。": "to read and switch modes, with runtime and generation for conflict protection.", "过滤迟到快照，": "filters late snapshots,", "通过平台注入的策略恢复连接。": "and restores the connection through a platform-injected strategy.", "发送类型化": "sends typed", "；省略时显式使用": "; when omitted, it explicitly uses", "使用设备身份和 Ed25519 私钥完成挑战签名，换取短期 device token。": "uses the device identity and Ed25519 private key to sign the challenge and obtain a short-lived device token.", "，设备不解析业务命令，也不把模型名、阈值、目标模式或语言方向放进事件。": ", and the device neither parses business commands nor puts model names, thresholds, target modes, or language directions into events.",
  "English · 输出": "English · output", "介绍页只承诺已经验证的能力，更多终端和集成会逐步开放。P0 关注的是当前这一场交流，而不是长期档案或后台工作区。": "This site only promises verified capabilities. More endpoints and integrations will open over time; P0 focuses on the conversation at hand, not a long-term archive or admin workspace.", "产品需求文档（Issue #302）": "Product requirements (Issue #302)", "架构总览": "Architecture overview", "P0 协议设计": "P0 contract design", "开发说明": "Development guide",
  "实时会话": "Live session", "记录与投递": "Records and delivery", "Web 入口与 npm 脚本": "Web entry and npm scripts", "API 与 Realtime Audio": "API and Realtime Audio", "启动 PostgreSQL / Redis": "Start PostgreSQL / Redis", "真实模型": "Real models", "mock Provider 可离线运行": "Mock providers run offline", "从仓库根目录复制环境变量示例，并为 API 与 Realtime Audio 配置共享的票据密钥和命令服务凭证。": "Copy the environment example from the repository root and configure the shared ticket secret and command-service credentials for API and Realtime Audio.", "根目录 · .env": "Repository root · .env", "本地普通音频链路默认使用 mock ASR、翻译和 TTS；要验证真实语音命令，还需要配置 Qwen 意图识别，并将 ASR 切换为可用的真实 Provider。": "The local voice path uses mock ASR, translation, and TTS by default. To verify real voice commands, configure Qwen intent recognition and switch ASR to an available real provider.", "Windows 从仓库根目录启动 API、Realtime Audio 和 Docker 依赖：": "On Windows, start API, Realtime Audio, and Docker dependencies from the repository root:", "非 Windows 环境先导入 `.env`，再启动基础依赖和两个 Go 服务：": "On non-Windows systems, load `.env` first, then start the dependencies and the two Go services:", "复制 Web 环境变量示例后安装依赖，并启动本地开发服务器。": "Copy the Web environment example, install dependencies, and start the local development server.", "会话配置、字幕、播报与控制入口。": "Session setup, captions, playback, and controls.", "账户、会话、语言配置与实时连接票据。": "Accounts, sessions, language settings, and live connection tickets.", "WebRTC、VAD、ASR、翻译、TTS 与运行状态。": "WebRTC, VAD, ASR, translation, TTS, and runtime state.", "统一维护 REST、信令、实时事件、错误码和状态定义。": "The shared definitions for REST, signaling, live events, error codes, and state.", "提供 PostgreSQL、Redis/Valkey 和可选的 realtime 会话哈希网关。": "Provides PostgreSQL, Redis/Valkey, and an optional realtime session-hash gateway.", "一条实时链路": "One live path", "一条会话的职责边界": "Responsibilities within one session", "Device SDK 是面向硬件厂商和方案商的 Go 控制核心参考实现，提供会话、模式命令、唤醒事件、状态投影与弱网重连边界；具体芯片音频 HAL、WebRTC 和 KWS 模型由设备平台适配。": "Device SDK is a Go control-core reference implementation for hardware makers and solution partners. It defines sessions, mode commands, wake events, state projection, and reconnect boundaries; the device platform adapts the audio HAL, WebRTC, and KWS models.", "当前能力": "Current capabilities", "README / 开发说明": "README / development", "仓库 README": "Repository README", "产品需求文档（PRD）": "Product requirements (PRD)", "协议 / Contracts": "Protocols / contracts", "OpenAPI REST 契约": "OpenAPI REST contract", "AsyncAPI 实时事件": "AsyncAPI live events", "跨端契约说明": "Cross-platform contract guide", "设备 / 部署": "Device / deployment", "Device SDK 接入说明": "Device SDK integration guide", "生产部署文档": "Production deployment guide", "本地基础设施说明": "Local infrastructure guide", "设计与范围": "Design and scope", "Lingow 架构总览": "Lingow architecture overview", "Lingow 模块详细设计": "Lingow module design", "Lingow P0 协议设计": "Lingow P0 contract design",
  "首页": "Home", "产品": "Product", "文档": "Docs", "关于 Lingow": "About Lingow",
  "实时语音系统 · Web 可运行": "Real-time voice system · Web is live",
  "让两种语言，": "Let two languages", "在同一场对话里": "move naturally", "自然来回。": "through one conversation.",
  "Lingow 把语音识别、翻译和播报连接在同一条实时会话中，也支持通过声音完成命令和模式切换。": "Lingow connects speech recognition, translation, and playback in one live session, while voice commands can switch modes without breaking the conversation.",
  "立即打开 Web 体验": "Open the Web experience", "查看文档": "Read the docs", "双语实时会话示意": "Bilingual live session preview",
  "同一场对话": "One conversation", "两种语言": "Two languages", "中文 · 输入": "Chinese · input", "我们可以从今天的议程开始吗？": "Shall we start with today's agenda?", "正在播报": "Speaking",
  "先看事实，": "Start with facts", "再开始体验。": "then try it.", "Web 当前可运行": "Web is currently runnable", "浏览器是现在主要的联调与体验入口。": "The browser is the primary integration and trial entry point today.",
  "WebRTC 实时音频链路": "WebRTC live audio path", "音频媒体与控制事件在同一条实时会话中完成。": "Audio media and control events share the same live session.", "P0 不保存原始音频": "P0 does not retain raw audio", "长期保存文本 Final Turn 和用量事实。": "Only text Final Turns and usage facts are retained long term.",
  "同一条会话，": "One session,", "两种工作方式。": "two ways to work.", "按现场需要选择入口。模式只改变业务处理方式，不重建已经建立的实时连接。": "Choose the entry point that fits the moment. Switching modes changes handling, not the established live connection.", "选择工作方式": "Choose a work mode", "面对面同传": "Face-to-face interpreting", "AI 语音助手": "AI voice assistant",
  "保持对话节奏。": "keep the conversation moving.", "用声音完成下一步。": "take the next step by voice.", "为一组双语配置开启临时会话。系统自动识别发言，完成翻译，在句末播报，并允许另一方随时抢话。": "Start a temporary session with a bilingual pair. Lingow detects speech, translates it, speaks at sentence boundaries, and lets either person take the floor.", "双语配置与自动语言识别": "Bilingual setup and automatic language detection", "流式 ASR、翻译与句末播报": "Streaming ASR, translation, and end-of-turn playback", "抢话打断，双方可以自然接话": "Interruption support for natural turn-taking",
  "唤醒 Lingow 后，用自然语言提问、执行命令或切换模式。助手与同传共用同一条 WebRTC 会话。": "Wake Lingow to ask questions, run commands, or switch modes in natural language. The assistant and interpreter share one WebRTC session.", "本地唤醒词“小灵小灵”": "Local wake word \"Xiao Ling Xiao Ling\"", "自然语言问答与语义命令": "Natural-language answers and commands", "不重建连接即可切换工作方式": "Switch modes without reconnecting",
  "输入": "Input", "处理": "Process", "输出": "Output", "两种语言的现场语音": "Live speech in two languages", "识别、翻译、固定当前 Turn": "Recognize, translate, and lock the current turn", "目标语言播报与可选字幕": "Target-language playback and optional captions", "唤醒词与自然语言命令": "Wake word and natural-language commands", "命令解释与助手响应": "Command interpretation and assistant response", "语音回复、字幕或模式切换": "Voice reply, captions, or mode switching",
  "麦克风": "Microphone", "采集现场语音": "Capture live speech", "找到一句话的边界": "Find utterance boundaries", "把声音变成文本": "Turn speech into text", "翻译": "Translate", "转换到另一种语言": "Convert to the other language", "TTS / 字幕 / 企业微信": "TTS / captions / WeCom",
  "从麦克风到结果，": "From microphone to result,", "每一步都有位置。": "every step has a place.", "实时音频服务按顺序处理每个 Turn。输出可以是译音、字幕，也可以按配置投递到企业微信。": "The real-time audio service processes each turn in order. Output can be spoken, captioned, or delivered to WeCom by configuration.",
  "把数据边界，": "Make the data boundary", "提前说清楚。": "clear up front.", "实时处理完成后，不把原始语音作为长期档案保存。": "Raw speech is not kept as a long-term archive after processing.", "保存文本与用量事实": "Retain text and usage facts", "长期保存的是文本 Final Turn 和用于统计的用量事实。": "Long-term retention is limited to text Final Turns and usage facts for accounting.", "字幕和企业微信按配置启用": "Captions and WeCom are configurable", "字幕展示与消息投递都是可选输出，不默认打开。": "Caption display and message delivery are optional outputs and off by default.", "会话是临时会话": "Sessions are temporary", "参与者无需登记，创建会话即可开始面对面交流。": "Participants do not need profiles; create a session and start talking.", "先打开一次 Web 体验，": "Open the Web experience once,", "再决定下一步。": "then decide what comes next.",
  "一条实时会话，": "One live session,", "连接两种交流方式。": "connecting two ways to communicate.", "当前会话": "Current session", "临时会话": "Temporary session", "双向听译": "Bidirectional interpreting", "企业微信投递": "WeCom delivery", "工作方式": "Work modes", "根据现场，选择": "Choose what fits", "合适的声音入口。": "the moment.", "同一条实时会话支持两种方式：面对面同传负责双方互译，AI 助手负责问答、命令和模式切换。": "The same live session supports two modes: face-to-face interpreting for both directions, and an AI assistant for questions, commands, and mode switching.", "让双方用自己的语言交流。": "Let both people speak their own language.", "一场临时会话只需选择一组语言。系统会识别发言、翻译成对方语言，并在句末播报；字幕和消息投递可按需开启。": "Choose a language pair for a temporary session. Lingow detects speech, translates it for the other person, and speaks at the end of each sentence; captions and delivery are optional.", "不要求登录、注册或参与者登记": "No login, signup, or participant profile required", "语言配置固定在当前 Turn，修改从下一 Turn 生效": "Language settings stay fixed for the current turn and apply from the next", "双向听译或单向听译与企业微信投递": "Bidirectional or one-way interpreting with WeCom delivery", "双语会话 / zh-CN ↔ en-US": "Bilingual session / zh-CN ↔ en-US", "把下一步交给声音。": "Let voice handle the next step.", "Web 入口默认从助手模式开始。唤醒 Lingow 后，可以用自然语言提问、执行命令或切换到同传模式，整个过程不需要重新建立连接。": "The Web entry starts in assistant mode. Wake Lingow to ask questions, run commands, or switch to interpreting without rebuilding the connection.", "自然语言语义命令与助手问答": "Natural-language commands and assistant answers", "与 interpretation 模式共用一条 WebRTC 会话": "Shares one WebRTC session with interpretation mode",
  "Lingow 为面对面交流提供一条临时的实时会话：选择语言对后，可以进行双向同传，也可以将单向译文投递到企业微信。": "Lingow provides a temporary live session for face-to-face conversations. Choose a language pair for bidirectional interpreting or deliver one-way translations to WeCom.", "Lingow 是一个面向 Web、移动端和设备控制核心的 AI 语音助手与面对面同传系统。我们先把临时交流从开始到结束做得简单清楚，再逐步扩展到更多终端。": "Lingow is an AI voice assistant and face-to-face interpreting system spanning Web, mobile, and a device control core. We make temporary conversations clear from start to finish, then expand to more endpoints.", "客户端负责采集、播放和交互；API 管理长期业务状态；Realtime Audio 负责 WebRTC 连接和运行时状态。跨端共享的数据和状态，统一由 contracts 定义。": "Clients capture, play, and handle interaction; the API owns long-lived business state; Realtime Audio owns WebRTC connections and runtime state. Shared data and state are defined once in contracts.", "会话配置、字幕、播报、唤醒和控制入口。": "Session setup, captions, playback, wake-up, and controls.", "账户、会话、语言配置、Final Turn、用量和异步消息。": "Accounts, sessions, language settings, Final Turns, usage, and async messages.", "WebRTC、VAD、ASR、翻译、TTS、打断和运行状态。": "WebRTC, VAD, ASR, translation, TTS, interruption, and runtime state.", "REST、信令、实时事件、错误码和状态定义的唯一来源。": "The single source for REST, signaling, live events, error codes, and state definitions.", "项目把可运行入口、控制核心和平台适配分开定义，下面按这几个边界说明当前进展。": "The project separates runnable entries, the control core, and platform adapters; the sections below describe progress at each boundary.", "主要可运行入口": "Primary runnable entry", "Next.js Web 负责会话、语言设置、WebRTC、字幕、助手回复和 TTS 交互，默认从 AI 助手模式开始。": "Next.js Web handles sessions, language settings, WebRTC, captions, assistant replies, and TTS, starting in assistant mode.", "控制面核心": "Control-plane core", "Mobile 当前提供可编译、可测试的 TypeScript 控制面核心，尚未绑定 UI、PeerConnection 或原生 KWS。": "Mobile currently provides a compilable, testable TypeScript control core without UI, PeerConnection, or native KWS bindings.", "接口而非成品硬件": "Interfaces, not finished hardware", "Device SDK 提供鉴权、会话、模式、唤醒事件和重连边界；具体音频 HAL、WebRTC 和 KWS 模型由平台适配。": "Device SDK defines authentication, sessions, modes, wake events, and reconnect boundaries; the platform adapts the audio HAL, WebRTC, and KWS models.", "明确不承诺": "Explicitly out of scope", "当前不提供管理后台、订单、支付、发票、多人会议同传或硬件制造能力。": "Admin consoles, orders, payments, invoices, conference interpreting, and hardware manufacturing are not provided today.", "产品范围、架构和协议都公开在仓库中。可以先从对应文档开始，再进入代码和 Issue。": "Product scope, architecture, and protocols are public in the repository. Start with the relevant docs, then explore the code and issues.",
  "实时链路": "Live path", "每一次回应，": "Every response", "都有清晰的路径。": "has a clear path.", "音频通过 WebRTC 进入实时链路，依次经过 VAD、ASR 和翻译；确认后的结果再进入播报、字幕或消息投递。": "Audio enters over WebRTC and passes through VAD, ASR, and translation; confirmed results then go to playback, captions, or delivery.", "聆听": "Listen", "捕捉双方语音，保持对话节奏。": "Capture both voices and keep the rhythm.", "识别": "Recognize", "将连续声音转换为可理解的文本。": "Turn continuous speech into understandable text.", "在两个语言槽位之间完成实时转换。": "Translate in real time between the two language slots.", "传达": "Deliver", "通过语音、字幕或消息传递结果。": "Share results by voice, caption, or message.",
  "会话边界": "Session boundaries", "轻量开始，": "Start light,", "明确结束。": "end clearly.", "这里关注一场临时交流的完整生命周期，不涉及历史会话管理。": "This covers the full lifecycle of a temporary exchange, not historical session management.", "开始": "Start", "选择语言对后获取短期票据，建立 WebRTC 连接。": "Choose a language pair, get a short-lived ticket, and establish WebRTC.", "进行中": "In progress", "持续听音、处理并输出；新的有效发言可以打断当前译音。": "Listen, process, and output continuously; a new valid utterance can interrupt playback.", "运行状态": "Runtime state", "结束": "End", "停止采集和播放，重复结束请求不会产生副作用；服务端确认后释放实时资源。": "Stop capture and playback. Repeated end requests are harmless; resources are released after server confirmation.", "幂等结束": "Idempotent end", "输出与数据": "Output and data", "把结果送达，": "Deliver the result,", "不把原始音频留下。": "without keeping raw audio.", "长期保存的是文本 Final Turn 和用量事实；P0 不保存原始音频，字幕只是可选展示，音频仍是主要交流方式。": "Text Final Turns and usage facts are retained; P0 keeps no raw audio. Captions are optional, while audio remains the primary channel.", "两个方向都完成识别、翻译、文本记录和目标语言播报。": "Both directions are recognized, translated, recorded, and spoken in the target language.", "单向投递": "One-way delivery", "一侧播放译音，另一侧的有效文本结果可异步发送到已绑定的企业微信。": "Play interpreted audio on one side and asynchronously send the other side's valid text to a bound WeCom destination.", "可选展示": "Optional display", "有屏幕时展示原文、译文和状态；没有屏幕也能通过音频完成交流。": "Show source text, translation, and status when a screen is available; audio works without one.",
  "项目状态": "Project status", "Web 可运行入口": "Runnable Web entry", "Mobile 控制核心": "Mobile control core", "Device 平台适配": "Device platform adapters", "产品原则": "Product principles", "让技术退后一步，": "Let technology step back,", "让人回到对话里。": "so people can return to the conversation.", "把复杂度留在实时链路和协议边界里，使用者只需专注于眼前这场对话。": "Complexity belongs in the live path and protocol boundaries, so people can focus on the conversation in front of them.", "先听见": "Listen first", "把连续语音当成对话，而不是一串等待处理的文件。": "Treat continuous speech as a conversation, not a queue of files.", "再理解": "Understand next", "在双方语言之间建立自然的来回，不打断交流节奏。": "Create a natural exchange between languages without breaking the rhythm.", "能扩展": "Stay extensible", "用清晰的协议和控制边界连接更多终端与场景。": "Connect more devices and situations through clear protocols and control boundaries.", "系统架构": "System architecture", "三层职责，": "Three responsibilities,", "一条会话。": "one session.", "当前阶段": "Current stage", "把项目现状，": "Make the current state", "说明白。": "easy to understand.", "开放资料": "Open resources", "从公开资料，": "Start with public materials,", "了解每个决定。": "and understand each decision.", "从公开仓库开始，": "Start with the public repository,", "把问题聊具体。": "and make the questions concrete.", "查看 GitHub": "View on GitHub", "当前范围": "Current scope", "清楚知道": "Know clearly", "现在能做到什么。": "what works today.",
  "返回 Web 体验": "Back to Web", "查看仓库": "View repository", "文档固定操作": "Pinned documentation actions", "文档目录": "Documentation directory", "收起目录": "Collapse directory", "展开目录": "Expand directory", "快速开始": "Quick start", "核心能力": "Core capabilities", "产品概览": "Product overview", "当前边界": "Current scope", "入门": "Getting started", "系统": "System", "扩展": "Extensions", "资源": "Resources", "协议与事件": "Protocols and events", "相关文档": "Related docs", "产品简介": "Product overview", "它解决什么问题": "What problem it solves", "两种输出方式": "Two output modes", "一次会话如何开始": "How a session starts", "设备接入边界": "Device integration boundary", "一场会话 · 一个事实来源": "One session · one source of truth", "必需": "Required", "可选": "Optional", "复制": "Copy", "已复制": "Copied", "复制失败": "Copy failed", "回到顶部": "Back to top", "实时语音助手与面对面同传系统。": "Real-time voice assistant and face-to-face interpreting system.", "阅读开发文档": "Read developer docs", "Lingow 首页": "Lingow home", "主导航": "Main navigation", "移动端主导航": "Mobile main navigation", "当前": "Current",
  "Lingow 面向同一物理空间内的临时双语交流。用户选择一组语言对，使用现有音频终端开始会话，系统在这组语言内识别当前发言、翻译成另一种语言，并通过译音或企业微信投递帮助双方继续交流。": "Lingow is built for temporary bilingual conversations in the same physical space. Choose a language pair, start with an existing audio endpoint, and let Lingow recognize, translate, and deliver speech so both people can keep talking.",
  "双方没有共同语言时，仍能在同一场对话中自然来回交流。": "People can keep a natural exchange even without a shared language.", "交流是临时发生的，不需要先登录、注册或建立参与者资料。": "Sessions are temporary: no login, signup, or participant profiles.", "译音过长时，可通过单向输出和异步投递减少对交流节奏的阻塞。": "One-way output and asynchronous delivery prevent long playback from blocking the conversation.", "语言可能在交流中变化，会话内修改配置并从下一 Turn 生效。": "Language settings can change during a session and apply from the next turn.", "双方都听到目标语言译音，每个有效 Turn 都经过识别、翻译、Final Turn 保存和 TTS。": "Both sides hear target-language audio; each valid turn is recognized, translated, saved as a Final Turn, and spoken.", "单向听译与投递": "One-way interpreting and delivery", "一侧播放译音，另一侧的有效 Final Turn 异步发送到已绑定的企业微信目标。": "One side hears interpreted audio while valid Final Turns from the other side are sent asynchronously to a bound WeCom target.", "选择语言对与输出方式": "Choose a language pair and output mode", "在会话开始前确定当前支持的语言范围。": "Set the supported language range before the session begins.", "创建临时会话并建立实时连接": "Create a temporary session and live connection", "API 签发短期票据，Realtime Audio 建立 WebRTC 链路。": "The API issues a short-lived ticket and Realtime Audio establishes WebRTC.", "听音、处理、播放或投递": "Listen, process, play, or deliver", "每轮语音完成 VAD、ASR、翻译，再按输出配置继续。": "Each voice turn passes through VAD, ASR, and translation before following the output configuration.", "结束并释放资源": "End and release resources", "客户端停止采集和播放，服务端幂等结束并回收实时资源。": "The client stops capture and playback; the server ends the session idempotently and releases resources.",
  "Lingow 将语音入口、实时媒体链路和可扩展的设备边界组合成一条会话体验。": "Lingow combines voice entry points, a live media path, and extensible device boundaries into one session experience.", "支持唤醒词检测、自然语言命令、助手问答与模式切换。": "Wake-word detection, natural-language commands, assistant answers, and mode switching.", "在选定语言对内完成自动语言识别、流式 ASR、翻译与句末 TTS。": "Automatic language detection, streaming ASR, translation, and end-of-turn TTS for a selected language pair.", "通过 WebRTC 音频、可靠有序 DataChannel、运行状态和模式快照保持链路连续。": "Keep the path continuous with WebRTC audio, reliable ordered DataChannel messages, runtime state, and mode snapshots.", "保存文本 Final Turn 和用量事实，并按配置支持 Email、企业微信等异步投递。": "Retain text Final Turns and usage facts, with configurable asynchronous delivery to Email, WeCom, and more.", "Web 是当前主要可运行的联调入口，默认以 AI 助手模式创建新会话。": "Web is the primary runnable integration entry and starts new sessions in assistant mode.", "管理后台、订单、支付、发票、多人会议同传和硬件制造不属于当前产品范围。": "Admin consoles, orders, payments, invoices, conference interpreting, and hardware manufacturing are outside the current scope.", "本地联调由 API、Realtime Audio 与 Web 三部分组成。先启动后端依赖，再启动浏览器入口。": "Local integration uses API, Realtime Audio, and Web. Start backend dependencies first, then the browser entry.", "开始之前": "Before you begin", "需要本地可用的 Node.js 环境；完整语音会话还需要 API 与 Realtime Audio 服务。": "You need a local Node.js environment; a full voice session also requires API and Realtime Audio.", "准备环境": "Prepare the environment", "配置根环境": "Configure the root environment", "启动本地服务": "Start local services", "启动 Web 入口": "Start the Web entry", "默认地址": "Default addresses",
  "保持同一条会话": "Keep one session", "唤醒与模式切换应复用现有 Runtime 和 WebRTC 连接，不应为每次语音命令重建连接。": "Wake-up and mode changes should reuse the existing Runtime and WebRTC connection, not rebuild it for every voice command.", "事件方向": "Event direction", "平台适配边界": "Platform adapter boundary", "从系统结构、开发约定到协议和产品范围，按需要打开对应的设计资料。": "Open the design material you need, from system structure and development conventions to protocols and product scope.",
  "Lingow 将客户端、API 控制面和 Realtime Audio 媒体面分开：客户端只负责采集、播放和交互，API 拥有长期业务状态，Realtime Audio 拥有实时连接与运行状态。": "Lingow separates clients, the API control plane, and the Realtime Audio media plane: clients capture, play, and interact; the API owns long-lived business state; Realtime Audio owns live connections and runtime state.", "Web 负责用户交互、会话 API 调用与字幕、TTS 呈现。": "Web handles user interaction, session API calls, captions, and TTS presentation.", "API 负责账户、会话、语言配置、Final Turn、用量和异步消息等长期业务状态。": "The API owns long-lived account, session, language, Final Turn, usage, and async message state.", "Realtime Audio 负责 WebRTC 连接、VAD、ASR、翻译、TTS、打断和运行时状态机。": "Realtime Audio owns WebRTC, VAD, ASR, translation, TTS, interruption, and the runtime state machine.", "API 只查询实时状态快照，不重复维护实时播放状态机；跨服务数据必须通过 contracts 并支持幂等、重试和可靠投递。": "The API reads runtime snapshots without duplicating playback state; cross-service data goes through contracts with idempotency, retries, and reliable delivery.", "控制面与实时面使用不同契约表达各自的边界。它们由同一个会话状态连接，但不重复维护媒体运行态。": "The control and real-time planes use separate contracts for their boundaries. One session state connects them without duplicating media runtime state.", "账户、会话、语言配置、历史记录与连接票据。": "Accounts, sessions, language settings, history, and connection tickets.", "运行状态、字幕、助手回复、模式切换与错误事件。": "Runtime state, captions, assistant replies, mode changes, and error events.", "共享 realtime、records、语言配置和错误码类型，避免各端重复定义 DTO。": "Shared realtime, records, language, and error-code types prevent duplicate DTOs.", "契约唯一来源": "Single source of truth", "实时连接票据": "Live connection ticket", "正式联调由 API 为已创建的语音会话签发实时连接票据。Web 在建立 WebRTC 连接前获取该票据。": "For integration, the API issues a live connection ticket for a created voice session. Web obtains it before opening WebRTC.", "媒体与事件方向": "Media and event direction", "音频媒体使用 WebRTC audio track，不通过 WebSocket 传输。": "Audio media uses a WebRTC audio track, not WebSocket.", "WebRTC DataChannel 或 realtime HTTP 接口承载控制事件；API 不交换 SDP/ICE。": "WebRTC DataChannel or realtime HTTP carries control events; the API does not exchange SDP/ICE.", "本地开发旁路仅用于显式启用的": "The local development bypass is only for explicitly enabled", "环境，不应用于生产部署。": "environments and must not be used in production.", "固定唤醒词“小灵小灵”命中后只发送": "After the fixed wake word is detected, the device only sends", "同一份麦克风 PCM 持续进入板载 KWS 和既有 WebRTC 编码链路；KWS、音频 HAL、PeerConnection 生命周期由平台实现。": "The same microphone PCM feeds onboard KWS and the existing WebRTC encoder; the platform owns KWS, audio HAL, and PeerConnection lifecycles.", "设备不能保存用户 Access Token 或 Refresh Token；生产固件使用": "Devices must not store user Access or Refresh Tokens; production firmware uses", "，只在短期 device token 有效时请求 realtime ticket。": " and requests a realtime ticket only while a short-lived device token is valid.",
};

function translateText(value: string, locale: Locale) {
  if (locale === "zh") return value;
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const core = value.trim();
  return `${leading}${translations[core] ?? core}${trailing}`;
}

type LocaleContextValue = { locale: Locale; setLocale: (locale: Locale) => void };
const LocaleContext = createContext<LocaleContextValue | null>(null);

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("zh");
  const restoring = useRef(true);
  useEffect(() => {
    const stored = window.localStorage.getItem("lingow-intro-locale");
    const timer = window.setTimeout(() => {
      if (stored === "en" || stored === "zh") setLocaleState(stored);
      restoring.current = false;
      document.documentElement.lang = stored === "en" ? "en" : "zh-CN";
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => {
    if (restoring.current) return;
    document.documentElement.lang = locale === "en" ? "en" : "zh-CN";
    window.localStorage.setItem("lingow-intro-locale", locale);
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale: (next: Locale) => setLocaleState(next) }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale() {
  const context = useContext(LocaleContext);
  if (!context) throw new Error("useLocale must be used inside LocaleProvider");
  return context;
}

function localizeNode(node: ReactNode, locale: Locale): ReactNode {
  if (typeof node === "string") return translateText(node, locale);
  if (Array.isArray(node)) return Children.toArray(node).map((child) => localizeNode(child, locale));
  if (!isValidElement(node) || node.type === "code" || node.type === "pre") return node;
  const props = node.props as { children?: ReactNode };
  return Object.prototype.hasOwnProperty.call(props, "children")
    ? cloneElement(node, undefined, localizeNode(props.children, locale))
    : node;
}

export function Localized({ children }: { children: ReactNode }) {
  const { locale } = useLocale();
  if (locale === "zh") return <>{children}</>;
  return <>{localizeNode(children, locale)}</>;
}

export function translate(value: string, locale: Locale) {
  return translateText(value, locale);
}
