package realtimev1

import (
	"errors"
	"fmt"
	"strings"
	"unicode/utf8"
)

const (
	// ControlProtocolVersion is the JSON protocol spoken over the control DataChannel.
	ControlProtocolVersion = 1
	// ControlDataChannelLabel identifies the client-created, reliable ordered control channel.
	ControlDataChannelLabel = "lingow-control-v1"

	maxControlRequestIDLength    = 128
	maxControlRuntimeIDLength    = 128
	maxControlOperationIDLength  = 256
	maxControlErrorMessageLength = 512
)

var ErrInvalidControlMessage = errors.New("invalid realtime control message")

// ControlMessageType identifies one typed message carried by the shared control DataChannel.
type ControlMessageType string

const (
	ControlMessageModeSwitch       ControlMessageType = "mode.switch"
	ControlMessageModeSwitchResult ControlMessageType = "mode.switch.result"
	ControlMessageError            ControlMessageType = "control.error"
)

// Valid reports whether the message type belongs to control protocol v1.
func (messageType ControlMessageType) Valid() bool {
	switch messageType {
	case ControlMessageModeSwitch, ControlMessageModeSwitchResult, ControlMessageError:
		return true
	default:
		return false
	}
}

// ControlModeSwitchCommand contains only client-controlled mode-switch fields. Session identity
// comes from the authenticated PeerConnection, while trace identity is generated by realtime.
type ControlModeSwitchCommand struct {
	RuntimeInstanceID  string `json:"runtime_instance_id"`
	OperationID        string `json:"operation_id"`
	ExpectedGeneration int64  `json:"expected_generation"`
	TargetMode         Mode   `json:"target_mode"`
}

// Validate rejects commands that cannot safely be promoted to a SwitchModeCommand.
func (command ControlModeSwitchCommand) Validate() error {
	switch {
	case !validControlID(command.RuntimeInstanceID, maxControlRuntimeIDLength):
		return invalidControlField("command.runtime_instance_id")
	case !validControlID(command.OperationID, maxControlOperationIDLength):
		return invalidControlField("command.operation_id")
	case command.ExpectedGeneration < 1:
		return invalidControlField("command.expected_generation")
	case !command.TargetMode.Valid():
		return invalidControlField("command.target_mode")
	default:
		return nil
	}
}

// ControlModeSwitchRequest is the only client-to-server command in protocol v1. RequestID
// correlates one transport exchange; OperationID remains the runtime idempotency identity.
type ControlModeSwitchRequest struct {
	ProtocolVersion int                      `json:"protocol_version"`
	Type            ControlMessageType       `json:"type"`
	RequestID       string                   `json:"request_id"`
	Command         ControlModeSwitchCommand `json:"command"`
}

// Validate enforces the complete v1 mode-switch request contract.
func (request ControlModeSwitchRequest) Validate() error {
	switch {
	case request.ProtocolVersion != ControlProtocolVersion:
		return invalidControlField("protocol_version")
	case request.Type != ControlMessageModeSwitch:
		return invalidControlField("type")
	case !validControlID(request.RequestID, maxControlRequestIDLength):
		return invalidControlField("request_id")
	default:
		return request.Command.Validate()
	}
}

// ControlError is a stable machine-readable failure returned on the control DataChannel.
type ControlError struct {
	Code    ControlPlaneErrorCode `json:"code"`
	Message string                `json:"message"`
}

// Validate rejects unknown error codes and empty or unbounded display messages.
func (controlError ControlError) Validate() error {
	if !controlError.Code.Valid() {
		return invalidControlField("error.code")
	}
	if !validControlText(controlError.Message, maxControlErrorMessageLength) {
		return invalidControlField("error.message")
	}
	return nil
}

// ControlResponse returns either a successful mode result or one typed control error. RequestID
// may be absent only when malformed input could not be decoded far enough for correlation.
type ControlResponse struct {
	ProtocolVersion int                `json:"protocol_version"`
	Type            ControlMessageType `json:"type"`
	RequestID       string             `json:"request_id,omitempty"`
	Result          *SwitchModeResult  `json:"result,omitempty"`
	Error           *ControlError      `json:"error,omitempty"`
}

// Validate enforces message type, correlation, and the result/error exclusive union.
func (response ControlResponse) Validate() error {
	if response.ProtocolVersion != ControlProtocolVersion {
		return invalidControlField("protocol_version")
	}
	if response.RequestID != "" && !validControlID(response.RequestID, maxControlRequestIDLength) {
		return invalidControlField("request_id")
	}
	switch response.Type {
	case ControlMessageModeSwitchResult:
		if response.RequestID == "" || response.Result == nil || response.Error != nil {
			return invalidControlField("result")
		}
		return validateControlModeResult(*response.Result)
	case ControlMessageError:
		if response.Result != nil || response.Error == nil {
			return invalidControlField("error")
		}
		return response.Error.Validate()
	default:
		return invalidControlField("type")
	}
}

func validateControlModeResult(result SwitchModeResult) error {
	state := result.State
	switch {
	case !validControlID(result.OperationID, maxControlOperationIDLength):
		return invalidControlField("result.operation_id")
	case !result.Status.Valid():
		return invalidControlField("result.status")
	case strings.TrimSpace(state.SessionID) == "":
		return invalidControlField("result.state.session_id")
	case !validControlID(state.RuntimeInstanceID, maxControlRuntimeIDLength):
		return invalidControlField("result.state.runtime_instance_id")
	case !state.ActiveMode.Valid():
		return invalidControlField("result.state.active_mode")
	case state.Generation < 1:
		return invalidControlField("result.state.generation")
	case !state.Phase.Valid():
		return invalidControlField("result.state.phase")
	case state.LastOperationID == nil || *state.LastOperationID != result.OperationID:
		return invalidControlField("result.state.last_operation_id")
	case state.UpdatedAt.IsZero():
		return invalidControlField("result.state.updated_at")
	default:
		return nil
	}
}

func validControlID(value string, maxLength int) bool {
	return validControlText(value, maxLength) && !strings.ContainsAny(value, "\r\n\t")
}

func validControlText(value string, maxLength int) bool {
	return utf8.ValidString(value) && strings.TrimSpace(value) != "" && utf8.RuneCountInString(value) <= maxLength
}

func invalidControlField(field string) error {
	return fmt.Errorf("%w: %s", ErrInvalidControlMessage, field)
}
